#!/bin/bash

echo "This is insecure see https://create-react-app.dev/docs/proxying-api-requests-in-development/ for potential remedy"

cd /home/nigel/data-portal/react-client
HOST=0.0.0.0 DANGEROUSLY_DISABLE_HOST_CHECK=true npm start
